version: '3.7'
services:
  api:
    build: .
    image: 'example-api'
    ports:
      - '8600:8600'
    networks:
      - system
    depends_on:
      - db
  db:
    image: mysql:8
    ports:
      - '3306:3306'
    restart: 'unless-stopped'
    networks:
      - system
    volumes:
      - db-volume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=hoplin1234!
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=board
networks:
  system:
    driver: bridge
volumes:
  db-volume:
    external: false
